### ISSUE TITLE
Ajustes no projeto

### ISSUE THREAD

**Issue by oliveiralex** [alexsandromachado/movieflix#1]
Olá, estou corrigindo o seu trabalho.

Por gentileza, ajuste o seu projeto para incluir o seu backend para que possamos avaliar. No projeto foi incluído somente o frontend. Qualquer dúvida estou a disposição.

Abraço e bons estudos

**Comment by alexsandromachado** [comment]
Olá, @oliveiralex, backend incluído.

Abraço!
